Moved container attributes to the registry
open-telemetry/semantic-conventions pull request #417
Opened 2023-10-17 08:49 UTC by ChrsMark

## Changes

Refactoring: moves `container.*` attributes to the attributes registry

## Merge requirement checklist

* [x] [CONTRIBUTING.md](https://github.com/open-telemetry/semantic-conventions/blob/main/CONTRIBUTING.md) guidelines followed.
* [ ] [CHANGELOG.md](https://github.com/open-telemetry/semantic-conventions/blob/main/CHANGELOG.md) updated for non-trivial changes. (Not applicable)
* [ ] [schema-next.yaml](https://github.com/open-telemetry/semantic-conventions/blob/main/schema-next.yaml) updated with changes to existing conventions. (Not applicable)

2023-10-17 11:22 UTC, trisch-me commented on model/registry/container.yaml
> +        requirement_level: opt_in
`requirement_level` doesn't belong to the registry, it should be defined in the file where attribute is used

2023-10-17 11:23 UTC, trisch-me commented on model/resource/container.yaml
> +      - ref: container.command
` requirement_level: opt_in` should stay here

2023-10-17 11:23 UTC, trisch-me requested changes
please update the `requirement level`, otherwise lgtm

2023-10-18 15:17 UTC, joaopgrassi requested changes

2023-10-18 20:40 UTC, ChrsMark commented on docs/resource/container.md
> -| `container.id` | string | Container ID. Usually a UUID, as for example used to [identify Docker containers](https://docs.docker.com/engine/reference/run/#container-identification). The UUID might b
Slipped during the refactoring 🤦🏽 thank's!

2023-10-23 10:16 UTC, trisch-me approved these changes

2023-10-26 10:42 UTC, AlexanderWert requested changes

2023-10-26 10:42 UTC, AlexanderWert commented on docs/attributes-registry/container.md
> +## Open Container Initiative (OCI)
We should have a separate markdown file for each top-level namespace. So let's move this into a separate `oci.md` file.

Otherwise, LGTM.

2023-10-26 11:45 UTC, AlexanderWert commented on docs/attributes-registry/container.md
> +## Open Container Initiative (OCI)
only for the registry

2023-10-26 13:29 UTC, kaiyan-sheng approved these changes

2023-10-26 14:09 UTC, AlexanderWert approved these changes

2023-10-26 14:12 UTC, pyohannes approved these changes

2023-10-27 08:20 UTC, merged