move OS to registry
open-telemetry/semantic-conventions pull request #501
Opened 2023-11-09 15:51 UTC by trisch-me

## Changes

Refactoring: move OS to registry

## Merge requirement checklist

* [x] [CONTRIBUTING.md](https://github.com/open-telemetry/semantic-conventions/blob/main/CONTRIBUTING.md) guidelines followed.
* [ ] ~~[CHANGELOG.md](https://github.com/open-telemetry/semantic-conventions/blob/main/CHANGELOG.md) updated for non-trivial changes.~~
* [ ] ~~[schema-next.yaml](https://github.com/open-telemetry/semantic-conventions/blob/main/schema-next.yaml) updated with changes to existing conventions.~~

2023-11-09 16:12 UTC, AlexanderWert requested changes

2023-11-09 16:12 UTC, AlexanderWert commented on docs/resource/os.md
> -| Value  | Description |
You need to render the table with `full`, otherwise the values for `os.type` are not being rendered anymore.

2023-11-13 09:57 UTC, trisch-me commented
@AlexanderWert done, thanks for a hint

2023-11-13 11:24 UTC, AlexanderWert approved these changes

2023-11-13 11:24 UTC, AlexanderWert commented on docs/attributes-registry/os.md
> +## Operating system Attributes
```suggestion
## Operating System Attributes
```

2023-11-13 15:18 UTC, joaopgrassi approved these changes

2023-11-13 15:43 UTC, merged